CREATE USER C##QLCD_VNeID IDENTIFIED BY 123;

grant create session to  C##QLCD_VNeID;

grant create table to C##QLCD_VNeID;

alter user C##QLCD_VNeID quota 100M on users;

GRANT CREATE TABLE TO C##QLCD_VNeID;

GRANT CREATE SEQUENCE TO C##QLCD_VNeID;

GRANT UNLIMITED TABLESPACE TO C##QLCD_VNeID;
---------------------------------------------------------------------------------------------
DROP TABLE GiayPhepLaiXe CASCADE CONSTRAINTS;
DROP TABLE CongDan CASCADE CONSTRAINTS;
DROP TABLE HoKhau CASCADE CONSTRAINTS;
DROP TABLE LoaiBangLai CASCADE CONSTRAINTS;

CREATE TABLE LoaiBangLai (
    loaibang_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Tự động tăng
    ten_banglai VARCHAR2(20),
    phuongtien_lai NVARCHAR2(100) NOT NULL
);


CREATE TABLE HoKhau (
    hokhau_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Tự động tăng
    dia_chi NVARCHAR2(200) NOT NULL,
    phuong NVARCHAR2(30) NOT NULL,
    quan NVARCHAR2(30) NOT NULL,
    thanh_pho NVARCHAR2(30),
    tinh NVARCHAR2(30) NOT NULL,
    ngay_tao DATE
);


CREATE TABLE CongDan (
    congdan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Tự động tăng
    ho_ten VARCHAR2(100) NOT NULL,
    ngay_sinh DATE NOT NULL,
    gioi_tinh VARCHAR2(10) CHECK (gioi_tinh IN ('Nam', 'Nữ')),
    dien_thoai VARCHAR2(15) NOT NULL,
    email VARCHAR2(100),
    hokhau_id NUMBER,
    giayphep_id NUMBER,
    diachi NVARCHAR2(100) NOT NULL
);


CREATE TABLE GiayPhepLaiXe (
    giayphep_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Tự động tăng
    congdan_id NUMBER NOT NULL,
    loaibang_id NUMBER NOT NULL,
    ngay_cap DATE NOT NULL,
    co_quan_cap NVARCHAR2(100) NOT NULL
);


ALTER TABLE CongDan
ADD CONSTRAINT fk_CongDan1 FOREIGN KEY (hokhau_id) REFERENCES HoKhau(hokhau_id);

ALTER TABLE CongDan
ADD CONSTRAINT fk_CongDan2 FOREIGN KEY (giayphep_id) REFERENCES GiayPhepLaiXe(giayphep_id);

ALTER TABLE GiayPhepLaiXe
ADD CONSTRAINT fk_gplx_congdan FOREIGN KEY (congdan_id) REFERENCES CongDan(congdan_id);

ALTER TABLE GiayPhepLaiXe
ADD CONSTRAINT fk_gplx_lbl FOREIGN KEY (loaibang_id) REFERENCES LoaiBangLai(loaibang_id);

NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1)

------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------
INSERT INTO LoaiBangLai (ten_banglai, phuongtien_lai) VALUES ('B1', 'Xe máy');
INSERT INTO LoaiBangLai (ten_banglai, phuongtien_lai) VALUES ('B2', 'Xe hơi dưới 9 chỗ');
INSERT INTO LoaiBangLai (ten_banglai, phuongtien_lai) VALUES ('C', 'Xe tải');

INSERT INTO HoKhau (dia_chi, phuong, quan, thanh_pho, tinh, ngay_tao) 
VALUES ('123 Đường ABC', 'Phường 1', 'Quận 1', 'TP HCM', 'TP HCM', TO_DATE('2020-01-01', 'YYYY-MM-DD'));

INSERT INTO HoKhau (dia_chi, phuong, quan, thanh_pho, tinh, ngay_tao) 
VALUES ('456 Đường DEF', 'Phường 2', 'Quận 2', 'TP HCM', 'TP HCM', TO_DATE('2021-05-15', 'YYYY-MM-DD'));

INSERT INTO HoKhau (dia_chi, phuong, quan, thanh_pho, tinh, ngay_tao) 
VALUES ('789 Đường GHI', 'Phường 3', 'Quận 3', 'Hà Nội', 'Hà Nội', TO_DATE('2019-10-20', 'YYYY-MM-DD'));

-- Lưu ý: Chúng ta cần chèn `hokhau_id` dựa trên giá trị tự tăng của bảng `HoKhau`.

INSERT INTO CongDan (ho_ten, ngay_sinh, gioi_tinh, dien_thoai, email, hokhau_id, diachi) 
VALUES ('Nguyễn Văn A', TO_DATE('1990-02-15', 'YYYY-MM-DD'), 'Nam', '0123456789', 'nguyenvana@example.com', 1, '123 Đường ABC');

INSERT INTO CongDan (ho_ten, ngay_sinh, gioi_tinh, dien_thoai, email, hokhau_id, diachi) 
VALUES ('Trần Thị B', TO_DATE('1985-11-10', 'YYYY-MM-DD'), 'Nữ', '0987654321', 'tranthib@example.com', 2, '456 Đường DEF');

INSERT INTO CongDan (ho_ten, ngay_sinh, gioi_tinh, dien_thoai, email, hokhau_id, diachi) 
VALUES ('Lê Văn C', TO_DATE('2000-06-25', 'YYYY-MM-DD'), 'Nam', '0934567890', 'levanc@example.com', 3, '789 Đường GHI');

-- Lưu ý: Chúng ta cần chèn `congdan_id` và `loaibang_id` dựa trên giá trị tự tăng của các bảng `CongDan` và `LoaiBangLai`.

INSERT INTO GiayPhepLaiXe (congdan_id, loaibang_id, ngay_cap, co_quan_cap) 
VALUES (1, 1, TO_DATE('2021-03-01', 'YYYY-MM-DD'), 'Sở GTVT TP HCM');

INSERT INTO GiayPhepLaiXe (congdan_id, loaibang_id, ngay_cap, co_quan_cap) 
VALUES (2, 2, TO_DATE('2019-07-20', 'YYYY-MM-DD'), 'Sở GTVT Hà Nội');

INSERT INTO GiayPhepLaiXe (congdan_id, loaibang_id, ngay_cap, co_quan_cap) 
VALUES (3, 3, TO_DATE('2022-08-15', 'YYYY-MM-DD'), 'Sở GTVT TP HCM');



select * from CongDan;
select * from GiayPhepLaiXe;
select * from HoKhau;
select * from LoaiBangLai;

